### ISSUE TITLE
Get bot running in personal Discord server and understand the code

### ISSUE THREAD

**Issue by jcgoble3** [jcgoble3/mrc-discord-bot#19]
Get familiar with the existing code and how the discord.py library works, and experiment with local tweaks to gain a better understanding of how the code works. Get the bot running on your own personal server (@jcgoble3 will provide instructions) for User Story #83. Write notes on what you have learned.

Proof of completion: Brief summary (a few sentences) explaining what you've learned about how the bot works, and a screenshot of a successful `!ping` command on your own server.

Due Sunday, March 14.

**Comment by jcgoble3** [comment]
Proof of completion: Brief summary (a few sentences) explaining what you've learned about how the bot works, and a screenshot of a successful `!ping` command on your own server.

(Because Mr. Buck requires proof.)

**Comment by sethsarchet** [comment]
Below is the required "ping" command to show that the bot is working.
I had never used VSCode, or really GitHub at all, so I was able to learn and experiment with cloning a repository, pushing things, pulling and so on. I learned about a lot of the cool functionality built into VSCode that lets you do things like committing pretty seamlessly. Also, learned how the bot does many of the things it does by looking through the source code. I was not sure how it could actually see users input from discord and do something with it, so looking through and seeing the @commands.command() lines helped clear that up.

![Bot Working Pic](https://user-images.githubusercontent.com/57191930/111051310-17ea8f00-8420-11eb-8ef9-1a3443a7c488.jpg)

**Comment by jluckenbill** [comment]
Screenshot of ping command in use to show discord bot was running on personal discord server:
![image](https://user-images.githubusercontent.com/6639870/111092683-1e0a6980-850d-11eb-9161-c7f8e62d39d5.png)

Screenshot of a simple function called hello, implemented in support of understanding the code:
![image](https://user-images.githubusercontent.com/6639870/111092775-63c73200-850d-11eb-97c5-62eff9d251e8.png)

API documentation for discord.py:
[https://discordpy.readthedocs.io/en/latest/](https://discordpy.readthedocs.io/en/latest/)

API documentation for discord command extension:
[https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#)

The discord bot top level run file is index.py. 
- Line 7 loads the configuration
- Lines 10 - 16 define the bot
- Lines 18-21 load the discord extensions (Cogs) into the bot
    - Cog documentation: [https://discordpy.readthedocs.io/en/latest/ext/commands/cogs.html#ext-commands-cogs](https://discordpy.readthedocs.io/en/latest/ext/commands/cogs.html#ext-commands-cogs)
- Line 24 runs the bot using the token supplied in the configuration file

To become more familiar with the code, I added a simple command to the info.py file. When triggered by entering !hello into the chat, the bot will respond with a greeting, addressing the user by name and asking them how they are today.

![image](https://user-images.githubusercontent.com/6639870/111093756-16988f80-8510-11eb-855a-b1709c1db245.png)

- ctx is a reference to the Context object
    - [https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#context](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#context)
- ctx.send() is a function that will send a message, in the form of a string, to the chat
    - [https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.Context.send](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.Context.send)

**Comment by NateDawg96** [comment]
I learned for the first time how to clone a GitHub repository and get the code running on my personal computer. I spent the sprint trying to become more familiar with the overall organization of the discord bot code. The "cogs" folder includes folders that separate the currently-implemented bot commands into categories by function. The "utils" folder contains various data used by the bot commands. The "index.py" file executes the bot. Below is a screenshot of a successful "!ping" command in my personal server.
![Sofware Development Bot Ping](https://user-images.githubusercontent.com/77446032/111383120-2e8e2180-867e-11eb-8b7f-897db6a87482.PNG)

**Comment by mdlubbers167** [comment]
![image](https://user-images.githubusercontent.com/47870066/111384862-60a08300-8680-11eb-811f-c623c1d89619.png)
I learned how to clone a GitHub repository and make changes to the files. This is the first class that I've had to use GitHub so it's all pretty new to me. I also got familiar with some commands in the windows terminal. I have done things from the terminal in Linux before so getting used to the different syntax wasn't too difficult. Looking into the files included with the repo, I learned that index.py is how you run the bot, like the executable for the bot. The "Cogs" folder contains multiple python files with commands for the bot. My favorite is the "fun" file which has commands like eightball, which gives a magic eight-ball response to a question. I then found the ping command in the "info.py" file. I used this command in the screenshot to show that the bot is up and running.

**Comment by jcgoble3** [comment]
Trevor removed from assignees as he has dropped the course.

**Comment by jcgoble3** [comment]
@dward118 Ping to remind you to close this out.

**Comment by dward118** [comment]
Below is a screenshot of the ping command being used in my discord server. I now know the proper steps in cloning a GitHub repository and setting up a discord bot for a server. Ive never had the opportunity to setting up a discord bot until recently and can use this skill for myself if I ever need to make a bot for whatever reason.
![Screenshot_1](https://user-images.githubusercontent.com/58888261/113212513-ddb52600-9244-11eb-88d8-a3b249ebe594.jpg)
