### ISSUE TITLE
Ask Mr. Buck about the definition of "trivial"

### ISSUE THREAD

**Issue by jcgoble3** [jcgoble3/mrc-discord-bot#23]
Ask Mr. Buck at the start of the class on Thursday about his definition of "trivial" in grading requirements.

Completion Criteria: Class recording in Collaborate Ultra contains question and summary of response is posted here.

**Comment by jluckenbill** [comment]
Question was asked in class and Mr. Buck said a non-trivial task should take more than 15 minutes to complete.
