### ISSUE TITLE
Design communication protocol for trivia function

### ISSUE THREAD

**Issue by jcgoble3** [jcgoble3/mrc-discord-bot#24]
Create a list of requirements (syntax, timing, etc.) and a control flow graph for the trivia function described in User Story #9 and post that design to issue #9.

Completion Criteria: Complete requirements for how the trivia command should behave from the user's perspective and a basic graph showing control flow exist as a comment to issue #9.

Due: Tuesday, March 23

**Comment by NateDawg96** [comment]
Completed - documents provided in a comment to issue #9.
