### ISSUE TITLE
Write questions and answers for the trivia command (Seth)

### ISSUE THREAD

**Issue by jcgoble3** [jcgoble3/mrc-discord-bot#29]
Write at least 5-10 questions for use with the trivia command in User Story #9. Questions should have answers that are one or two words. Questions/answers can be initially written as plaintext, then upon merging of the pull request associated with Task/Action #25, converted to code and a pull request filed.

Completion Criteria: At least 5 trivia questions (more would be great :smile:) with one- or two-word answers are prepared, coded in the format implemented in #25, and a pull request with that code is made.

Due: Thursday, March 25, or 72 hours after the pull request for #25 is merged, whichever is later

**Comment by sethsarchet** [comment]
Plain text version of the trivia questions:

Stockholm is the capital and largest city of what country?
Sweden

When did the website “Facebook” launch?
2004

T/F: The scientific name for the Southern Lights is Aurora Australis?
T

On average, Americans consume 100 pounds of what per second?
Chocolate

How many bones are there in the human body?
206

What does Na stand for on the periodic table?
Sodium

Which fictional city is the home of Batman?
Gotham

Which planet is closest to Earth?
Venus


In the US version of The Office, what is the name of the city they live in?
Scranton

Which U.S. State is the largest?
Alaska
